name: MLOps

on: [push]

jobs:
  dvc-and-mlflow:
    runs-on: [self-hosted] 
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set DVC Local Config
        run: |
          conda run -n mlops --no-capture-output \
          dvc config --local cache.dir /media/junspring/JunSpring2/dvc_cache2

      - name: DVC Data Update
        run: |
          conda run -n mlops --no-capture-output \
          dvc update data.dvc

      - name: Submit to Slurm (No Wait)
        env:
          LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu:/home/junspring/anaconda3/envs/mlops/lib
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          # 1. 로그 폴더가 없으면 에러가 날 수 있으므로 미리 생성
          mkdir -p logs
          
          # 2. sbatch 실행
          sbatch <<EOF
          #!/bin/bash
          #SBATCH --job-name=mlops_async
          #SBATCH --output=logs/result_%j.log
          #SBATCH --error=logs/error_%j.log
          #SBATCH --gres=gpu:1
          
          source ~/anaconda3/etc/profile.d/conda.sh
          conda activate mlops
          
          python train.py
          EOF

    #   - name: Push Results to Jetson
    #     run: |
    #       conda run -n mlops --no-capture-output \
    #       dvc push -r jetson

      # - name: Deploy Model
      #   run: |
      #     conda activate mlops
      #     pkill -f "mlflow models serve" || true
      #     mlflow models serve -m "models:/CatsDogsModel/Production" -p 1234 --no-conda --host 0.0.0.0 &